language: go
go:
  - 1.5
sudo: false
services:
  - postgresql
addons:
  postgresql: "9.3"
install:
  - export GOPATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH
  - export PATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH
